apiVersion: v1
kind: Service
metadata:
  name: trtIzle
  labels:
    app: trtIzle
  annotations:
    maesh.containo.us/traffic-type: "http"
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: trtIzle
  selector:
    app: trtIzle